plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tweakied.spinforenterprise'
    compileSdk 34

    defaultConfig {
        applicationId "com.tweakied.spinforenterprise"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'org.json:json:20231013'
    implementation 'com.google.android.gms:play-services-location:21.2.0'
}

configurations.all {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == 'org.jetbrains.kotlin'
                && details.requested.name.startsWith('kotlin-stdlib')) {
            details.useVersion '1.9.24'
        }
    }
}
